### ISSUE TITLE
Bug: Can't save a repo edit

### ISSUE THREAD

**Issue by AnthonyFuller** [atampy25/glacierkit#17] opened 2024-11-12 11:48 UTC
# The issue

## Reproduction steps

1. Open `[assembly:/repository/pro.repo].pc_repo` in the editor.
2. Find `b0f87b4e-a41c-4771-8c74-f56574129679`
3. Change `ModelSkinSelections` to `[0, 4, 4, 0, 0, 0, 0, 0, 3, 0, 0]`
4. Try to save.

## Expected behaviour

It opens a file dialog where I can choose where to save it.

## Observed behaviour

It errors (see logs)

## Logs

`[2024-11-12][11:44:51][TRACE][app] Sending request: Global(ErrorReport { error: "Thread panic: called `Option::unwrap()` on a `None` value" })`

**Comment by atampy25** [comment] 2024-11-14 16:02
Duplicate of #9

**Closed by atampy25** 2024-11-14 16:02 UTC
Labels: issue
